
name: deployee node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        host: ${{ secrets.UBUNTU_IP }}
        username: ${{ secrets.UBUNTU_USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        publish_dir: erp_frontend
        script: |
           cd erp_frontend
           git clone git@github.com:vedanshu-insonix/erp-react-frontend.git
